language: go

arch:
  - amd64

go:
  - 1.14.x
  - 1.15.x
  - 1.x

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.35.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.0

script:
  - golangci-lint run
  - go test -v

matrix:
  allow_failures:
    - go: master
  fast_finish: true
